### ISSUE TITLE
run example error No such var: string/starts-with?

### ISSUE THREAD

**Issue by yzhannah** [tmarble/webica#11]
java.lang.RuntimeException: No such var: string/starts-with?
clojure.lang.ExceptionInfo: No such var: string/starts-with?
    file: "avenir/utils.cljc"
    line: 197

When I tried to run the example, I met the error above. Any hint on how to solve it?

**Comment by tmarble** [comment]
This shouldn't be a problem if you are using Clojure 1.8 (or later):
https://clojuredocs.org/clojure.string/starts-with_q

From the REPL:
```clojure
boot.user> (in-ns 'webica.core)
#namespace[webica.core]
webica.core> *clojure-version*
{:major 1, :minor 8, :incremental 0, :qualifier nil}
webica.core> (:java-version env)
"1.8.0_131"
webica.core> (string/starts-with? "webica" "web")
true
webica.core> 
```
Alternatively you could start avenir up in dual REPL mode (see https://github.com/tmarble/tenzing3 for an example).

Let me know if that helps!

**Comment by yzhannah** [comment]
Hi Tom,

      After changing the boot version and changing the browser to be chrome, the example works well.
      I’m wandering is there more example available for webica? I’m writing a web driver to chat with our virtual recruiter to generate test data.
      Thanks a lot for you efforts.
      Have a good day!

 Best,
Yihan

**Comment by tmarble** [comment]
Alas I don't have more examples (nor proper API docs)... But there is enough interest I will try to work on these! Let me know if I can close this issue.

**Comment by tmarble** [comment]
What I can recommend in the mean time is look at the Javadocs for Selenium and play with webica in the REPL to get a feeling for what's possible.

**Comment by yzhannah** [comment]
I think it’s okay to close it now. Thanks :)

**Comment by yzhannah** [comment]
Thanks for your tips:)
