### ISSUE TITLE
start and close chrome multiple times

### ISSUE THREAD

**Issue by yzhannah** [tmarble/webica#14]
I'm trying to let the web driver start and close the chrome multiple times.
 I tired the following method, which threw an exception

(loop [x 0]
      (when (< x 10)
          (chrome/start-chrome)
          (my function)
          (w/sleep 10)
          (browser/quit)
          (recur (+ x 1))))

Exception in thread "main" java.lang.RuntimeException: There is no zero-arg-constructor for org.openqa.selenium.remote.RemoteWebDriver, compiling:(/private/var/folders/z3/c4_msks50d189fzg6lmp5bmc0000gn/T/form-init8396518659152072947.clj:1:125)

Is there any tips on how to do so using your library?
Appreciate your help.

**Comment by priornix** [comment]
You need to call `(browser/quit)` passing in the driver created by `(chrome/start-chrome)`

```clojure
(let [driver (chrome/start-chrome)]
  (my-function)
  (browser/quit driver))
```

Whatever functions in `browser` namespace needs the `driver` argument, at least for Chrome

```clojure
(browser/get driver "http://www.example.com")
``` 

Also, it's not idiomatic to be using `loop` `recur`, unless in some special cases. The better way would be to:

```clojure
(doseq [x (range 10)]
  (let [driver (chrome/start-driver)]
    (browser/get driver "http://www.example.com")
    (w/sleep 10)
    (browser/quit driver)))
```

**Comment by yzhannah** [comment]
Got it, thanks a lot 👍

**Comment by yzhannah** [comment]
Hi, I tried it 

```
(defn testtest
  []
 (doseq [x (range 3)]
  (let [driver (chrome/start-chrome)]
    (browser/get driver "http://www.google.com")
    (w/sleep 10)
    (browser/quit driver))))
```

But got the following exception. 
```
Driver info: driver.version: RemoteWebDriver  org.openqa.selenium.remote.HttpCommandExecutor.execute (HttpCommandExecutor.java:134)
SessionNotFoundException Session ID is null. Using WebDriver after calling quit()?
```

I'm working under lein environment:
Leiningen 2.7.1 on Java 1.8.0_131 Java HotSpot(TM) 64-Bit Server VM

**Comment by priornix** [comment]
The default `(start-chrome)` function doesn't allow you to re-use the driver after it's been closed. I modified `start-chrome` and this works for me:

```clojure
(require '[me.raynes.fs :as fs])
(import '[org.openqa.selenium.chrome ChromeDriver])

(defn start-chrome [&[chromedriver]]
  (let [driver-prop "webdriver.chrome.driver"
        default-exe (System/getProperty driver-prop)
        chromedriver-system "/usr/lib/chromium/chromedriver"
        chromedriver-local "/usr/local/bin/chromedriver"
        chromedriver (or chromedriver
                     (if (and (not (empty? default-exe))
                           (fs/exists? default-exe))
                       default-exe)
                     (if (fs/exists? chromedriver-system)
                       chromedriver-system)
                     chromedriver-local)]
    (if-not (fs/exists? chromedriver)
      (throw
        (RuntimeException.
          (str "ERROR: chromedriver executable not found:" chromedriver))))
    (System/setProperty driver-prop chromedriver)
    ;; changed this to ChromeDriver
    (ChromeDriver.)))

(doseq [x (range 10)]
  (let [driver (start-chrome)]
    (browser/get driver "http://www.example.com")
    (Thread/sleep 3000)
    (browser/quit driver)))
```

**Comment by yzhannah** [comment]
That's make sense!  Thanks for your explanation. By the way, I tried to keep the browser open and clear cookies for each iteration which also work for me.

**Comment by tmarble** [comment]
@yzhannah so do you think this issue can be closed now?

**Comment by yzhannah** [comment]
Sure!
